USE [db_catalogo_servicios]
GO
/* No borrar comentarios
DROP TABLE IF EXISTS dbo.campo_servicio
DROP TABLE IF EXISTS dbo.solicitud
DROP TABLE IF EXISTS dbo.servicio
DROP TABLE IF EXISTS dbo.familia
DROP TABLE IF EXISTS dbo.formato
DROP TABLE IF EXISTS dbo.sede
DROP TABLE IF EXISTS dbo.direccion
DROP TABLE IF EXISTS dbo.campo
*/
--
--*********************************************************************
--TABLA Familia de servicios
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--DROP TABLE IF EXISTS [dbo].[familia]
CREATE TABLE [dbo].[familia](
	[FAMILIA_ID] [INT] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[ESTADO] [CHAR](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
	CONSTRAINT [PK_FAMILIA] PRIMARY KEY CLUSTERED
(
	[FAMILIA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[familia] ADD  CONSTRAINT [DF_FAMILIA_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
--*********************************************************************
--TABLA Formatos
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--DROP TABLE IF EXISTS [dbo].[formato]
CREATE TABLE [dbo].[formato](
	[FORMATO_ID] [INT] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[VERSION] [INT] NOT NULL,
	[ESTADO] [CHAR](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
	CONSTRAINT [PK_FORMATO] PRIMARY KEY CLUSTERED
(
	[FORMATO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[formato] ADD  CONSTRAINT [DF_FORMATO_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
ALTER TABLE [dbo].[formato] ADD  CONSTRAINT [DF_FORMATO_VERSION]  DEFAULT ((1)) FOR [VERSION]
GO
--*********************************************************************
--TABLA Campos
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
--DROP TABLE IF EXISTS [campo]
CREATE TABLE [dbo].[campo](
	[CAMPO_ID] [INT] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
    [ESTADO] [CHAR](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
 CONSTRAINT [PK_CAMPO] PRIMARY KEY CLUSTERED 
(
	[CAMPO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[campo] ADD  CONSTRAINT [DF_CAMPO_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO

SET ANSI_PADDING OFF
GO

--***********************************************************************
--TABLA Servicios
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
--DROP TABLE IF EXISTS [servicio]
CREATE TABLE [dbo].[servicio](
	[SERVICIO_ID] [INT] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](100) NOT NULL,
	FAMILIA_ID [INT],
	FORMATO_ID [INT],
	[ESTADO] [CHAR](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
 CONSTRAINT [PK_SERVICIO] PRIMARY KEY CLUSTERED 
(
	[SERVICIO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[servicio] ADD  CONSTRAINT [DF_SERVICIO_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO

ALTER TABLE [dbo].[servicio] ADD  CONSTRAINT [FK_SERVICIO_FORMATO]  FOREIGN KEY (FORMATO_ID) REFERENCES [dbo].[formato]([FORMATO_ID])
GO

ALTER TABLE [dbo].[servicio] ADD  CONSTRAINT [FK_SERVICIO_FAMILIA]  FOREIGN KEY (FAMILIA_ID) REFERENCES [dbo].[familia]([FAMILIA_ID])
GO

SET ANSI_PADDING OFF
GO
--***********************************************************************
--TABLA Campos por Servicio
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
--DROP TABLE IF EXISTS [campo_servicio]
CREATE TABLE [dbo].[campo_servicio](
	[CAMPO_SERVICIO_ID] [INT] IDENTITY(1,1) NOT NULL,
	[SERVICIO_ID] [INT],
	[CAMPO_ID] [INT],
	[ESTADO] [CHAR](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
 CONSTRAINT [PK_CAMPO_SERVICIO] PRIMARY KEY CLUSTERED 
(
	[CAMPO_SERVICIO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[campo_servicio] ADD  CONSTRAINT [DF_CSERVICIO_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO

ALTER TABLE [dbo].[campo_servicio] ADD  CONSTRAINT [FK_CAMPO]  FOREIGN KEY (CAMPO_ID) REFERENCES [dbo].[campo]([CAMPO_ID])
GO

ALTER TABLE [dbo].[campo_servicio] ADD  CONSTRAINT [FK_SERVICIO]  FOREIGN KEY (SERVICIO_ID) REFERENCES [dbo].[servicio]([SERVICIO_ID])
GO

SET ANSI_PADDING OFF
GO
--***********************************************************************
--TABLA Direcciones
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
----DROP TABLE IF EXISTS [direccion]
CREATE TABLE [dbo].[direccion](
	[ENUM_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENUM_PARENTCHLD1] [int] NOT NULL,
	[ENUM_PARENTCHLD2] [int] NOT NULL,
	[ENUM_DESC] [varchar] (200) NOT NULL,
	[ESTADO] [char](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
 CONSTRAINT [PK_DIRECCION] PRIMARY KEY CLUSTERED 
(
	[ENUM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[direccion] ADD  CONSTRAINT [DF_DIRECCION_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO

SET ANSI_PADDING OFF
GO
--***********************************************************************
--TABLA Sedes
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
----DROP TABLE IF EXISTS [sede]
CREATE TABLE [dbo].[sede](
	[SEDE_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar] (200) NOT NULL,
	[UBICACION] [varchar] (200) NOT NULL,
	[ESTADO] [char](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
 CONSTRAINT [PK_SEDE] PRIMARY KEY CLUSTERED 
(
	[SEDE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[sede] ADD  CONSTRAINT [DF_SEDE_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO

SET ANSI_PADDING OFF
GO
--***********************************************************************
--TABLA Solicitudes
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
----DROP TABLE IF EXISTS [solicitud]
CREATE TABLE [dbo].[solicitud](
	[SOLICITUD_ID] [INT] IDENTITY(1,1) NOT NULL,
	[COD_TICKET_GLPI] INT NOT NULL,
	[SERVICIO_ID] [INT],
	[NOMBRE_SOLICITANTE] VARCHAR(200) NOT NULL,
	[DIRECCION_ID] [INT],
	[SEDE_ID] [INT],
	[NOMBRE_CONTACTO] VARCHAR(200) NOT NULL,
	[ANEXO_CONTACTO] VARCHAR(500) NULL,
	[CELULAR_CONTACTO] VARCHAR(9) NOT NULL,
	[DOC_REFERENCIA] VARCHAR(100) NULL,
	[PRODUCTO] VARCHAR(200) NULL,
	[MODALIDAD] CHAR(1) NULL,
	[CANTIDAD] [INT],
	[CI_DESCRIPCION] VARCHAR(200) NULL,
	[CI_MARCA] VARCHAR(200) NULL,
	[CI_MODELO] VARCHAR(200) NULL,
	[CI_NRO_SERIE] VARCHAR(200) NULL,
	[CI_COD_SBN] VARCHAR(200) NULL,
	[EN_USO] CHAR(1) NULL,
	[OPERATIVO] CHAR(1) NULL,
	[MOTIVO] VARCHAR(15) NULL,
	[JUSTIFICACION] VARCHAR(300) NOT NULL,
	[ADJUNTO] [VARCHAR](200) NULL,
	[ESTADO] [CHAR](1) NOT NULL,
	USUARIO_CREACION VARCHAR (50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	USUARIO_ACTUALIZACION  VARCHAR (50) NULL,
	FECHA_ACTUALIZACION DATETIME NULL,
 CONSTRAINT [PK_SOLICITUD] PRIMARY KEY CLUSTERED 
(
	[SOLICITUD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[solicitud] ADD  CONSTRAINT [DF_SOLICITUD_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO

ALTER TABLE [dbo].[solicitud] ADD  CONSTRAINT [FK_SOLICITUD_SERVICIO]  FOREIGN KEY (SERVICIO_ID) REFERENCES [dbo].[servicio]([SERVICIO_ID])
GO

ALTER TABLE [dbo].[solicitud] ADD  CONSTRAINT [FK_SOLICITUD_SEDE]  FOREIGN KEY (SEDE_ID) REFERENCES [dbo].[sede]([SEDE_ID])
GO

ALTER TABLE [dbo].[solicitud] ADD  CONSTRAINT [FK_SOLICITUD_DIRECCION]  FOREIGN KEY (DIRECCION_ID) REFERENCES [dbo].[direccion]([ENUM_ID])
GO

ALTER TABLE [dbo].[solicitud] ADD  CONSTRAINT [DF_SOLICITUD_USUARIO_CREA]  DEFAULT ((USER_NAME())) FOR [USUARIO_CREACION]
GO

ALTER TABLE [dbo].[solicitud] ADD  CONSTRAINT [DF_SOLICITUD_FECHA_CRE]  DEFAULT ((GETDATE())) FOR [FECHA_CREACION]
GO

SET ANSI_PADDING OFF
GO